MODEL_PATH = "../model/llama-2-7b-chat.Q5_K_S.gguf"
DATA_PATH = "../data_mmd/"
DB_FAISS_PATH = "../index/"
CHROMA_PATH = "../chroma_db/"
CHROMA_COLLECTION = "financial_chatbot"
MODEL_DOWNLOAD_URL = "https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/resolve/main/llama-2-7b-chat.Q5_K_S.gguf?download=true"
MODEL_NAME = "gpt-3.5-turbo"
